apiVersion: v1
kind: Pod
metadata:
  name: product-api
  labels:
    component: products-api
spec:
  containers:
    - name: products-api
      image: webuxmotion/products-api
      ports:
        - containerPort: 5002